{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 19:28:34,919+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_3592\\3179714578.py\", line 38, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 19:28:34,929+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 19:28:35,245+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_3592\\3179714578.py\", line 38, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 19:28:35,245+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["MCX:GOLD25SEPFUT"]},"timestamp":"2025-08-28 19:28:36,710+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 19:28:37,232+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_3592\\3179714578.py\", line 38, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 19:28:37,232+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'symbol'","timestamp":"2025-08-28 19:45:22,445+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_10324\\1261671419.py\", line 13, in onmessage\n    print(\"Symbol:\",message['symbol'],  \"Volume: \",message['vol_traded_today'])\n                    ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'symbol' is missing in the response.","timestamp":"2025-08-28 19:45:22,445+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'symbol'","timestamp":"2025-08-28 19:45:22,756+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_10324\\1261671419.py\", line 13, in onmessage\n    print(\"Symbol:\",message['symbol'],  \"Volume: \",message['vol_traded_today'])\n                    ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'symbol' is missing in the response.","timestamp":"2025-08-28 19:45:22,756+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'symbol'","timestamp":"2025-08-28 19:45:24,943+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_10324\\1261671419.py\", line 13, in onmessage\n    print(\"Symbol:\",message['symbol'],  \"Volume: \",message['vol_traded_today'])\n                    ~~~~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'symbol' is missing in the response.","timestamp":"2025-08-28 19:45:24,952+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 20:05:16,583+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_11880\\715341082.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 20:05:16,583+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 20:05:16,752+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_11880\\715341082.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 20:05:16,752+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 20:05:18,256+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_11880\\715341082.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 20:05:18,256+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 20:42:21,008+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_11040\\1312989537.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 20:42:21,057+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 20:42:21,307+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_11040\\1312989537.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 20:42:21,307+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 20:42:23,266+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_11040\\1312989537.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 20:42:23,267+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 20:44:59,831+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_17768\\1263197631.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 20:44:59,831+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 20:45:00,051+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_17768\\1263197631.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 20:45:00,051+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 20:45:01,871+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_17768\\1263197631.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 20:45:01,871+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 21:01:05,547+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_7072\\1263197631.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 21:01:05,547+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 21:01:05,935+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_7072\\1263197631.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 21:01:05,935+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 21:01:07,737+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_7072\\1263197631.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 21:01:07,737+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 21:07:03,079+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_14088\\1263197631.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 21:07:03,087+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 21:07:03,270+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_14088\\1263197631.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 21:07:03,270+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'exch_feed_time'","timestamp":"2025-08-28 21:07:05,198+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"c:\\Python311\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"C:\\Users\\Rajeshree\\AppData\\Local\\Temp\\ipykernel_14088\\1263197631.py\", line 41, in onmessage\n    ms = message['exch_feed_time']\n         ~~~~~~~^^^^^^^^^^^^^^^^^^\nKeyError: 'exch_feed_time'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'exch_feed_time' is missing in the response.","timestamp":"2025-08-28 21:07:05,198+0530","service":"FyersDataSocket"}
